name: car-behavioral-cloning
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketIO==4.3.1
    - python-engineio==3.13.2
    - python-socketio==4.6.0
    - seaborn
    - pandas
    - imageio
    - pip
    - pip:
        - moviepy
        - tensorflow-gpu==1.1
        - keras==1.2
